name: decribe run
on: push
jobs:
  rundetails:
    runs-on: ubuntu-latest
    steps:
    - name: decribe the run
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Branch: $ {{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
        echo "Event: ${{ github.event_name }}"
        echo "Triggered by ${{ github.actor }}"
        echo "Runner: ${{ runner.os }}"
